"""
model_alignment.py

This module implements the RiskAlignmentModel, a representation alignment
component used within the HybridDL-ML-Ensemble architecture for early
mental health risk detection among university students.

The purpose of this module is to align learned latent representations
generated by upstream encoders or base models with clinically meaningful
mental health risk categories derived from survey indicators.

The alignment procedure improves semantic consistency between the
representation space and the target mental health labels. This is
particularly important when combining heterogeneous models such as
Random Forest, XGBoost, MLP, and CNN-1D within a stacked ensemble
framework.

Conceptual Overview
-------------------

In the proposed research architecture, feature representations are
generated from structured student data such as:

- Demographic indicators (age, gender, marital status)
- Academic performance indicators (CGPA, year of study)
- Psychological indicators (depression, anxiety, panic attacks)

These features are transformed into latent embeddings using encoding
mechanisms implemented in the encoder module.

However, these embeddings may not naturally align with clinically
interpretable mental health severity levels (0–3). Therefore, an
alignment model is introduced to improve correspondence between
embedding geometry and mental health risk categories.

Alignment Strategy
------------------

The alignment mechanism implemented here combines multiple principles:

1. Prototype Alignment
   Each class label is represented by a prototype vector (class center).
   Representations are pulled toward the prototype of their ground truth
   label.

2. Center Loss Regularization
   Encourages compact clusters in embedding space for each class.

3. Alignment Projection Layer
   A linear transformation learns to map encoder outputs into a
   clinically aligned embedding space.

4. Cross-Entropy Consistency
   A softmax classifier ensures aligned embeddings remain predictive.

Mathematically:

Let z_i be the representation for student i.

The alignment objective is:

    L_total = L_ce + lambda_c * L_center + lambda_p * L_prototype

Where:

    L_ce       = classification cross-entropy
    L_center   = distance to class centers
    L_prototype = prototype alignment loss

This improves clustering of mental health categories in latent space,
leading to better interpretability and stronger meta-learning signals
for the stacking ensemble.

Integration with the Project
----------------------------

This module integrates with the following components:

models.model_encoder
    Generates initial student feature embeddings.

models.model_base
    Provides base model abstraction used across the architecture.

strategies modules
    Use aligned representations to construct meta-features and
    decision strategies.

experiments modules
    Evaluate classification performance and statistical robustness.

The alignment model does not directly perform classification in the
main training pipeline. Instead, it refines feature representations so
that downstream meta-learning models (e.g., logistic regression
meta-learner) receive semantically organized features.

Design Principles
-----------------

- Deterministic and reproducible
- Fully documented for research collaboration
- Robust input validation
- Modular and extensible architecture
- Suitable for academic peer review

"""

from typing import Any, Dict, Optional, Tuple

import numpy as np

from models.model_base import BaseMentalHealthModel


class RiskAlignmentModel(BaseMentalHealthModel):
    """
    RiskAlignmentModel

    This class implements representation alignment between learned student
    feature embeddings and mental health risk categories.

    The model learns a projection matrix and class prototypes that organize
    latent representations into semantically meaningful clusters.

    Attributes
    ----------
    embedding_dim : int
        Dimensionality of input representations.

    num_classes : int
        Number of mental health severity classes.

    learning_rate : float
        Learning rate for alignment optimization.

    center_weight : float
        Weight applied to center loss.

    prototype_weight : float
        Weight applied to prototype alignment loss.

    projection_matrix : np.ndarray
        Linear projection used to transform representations.

    class_centers : np.ndarray
        Learned prototype vectors representing each class.

    classifier_weights : np.ndarray
        Linear classifier parameters for cross-entropy supervision.

    classifier_bias : np.ndarray
        Bias term for classifier.
    """

    def __init__(
        self,
        embedding_dim: int = 64,
        num_classes: int = 4,
        learning_rate: float = 0.001,
        center_weight: float = 0.5,
        prototype_weight: float = 0.5,
        seed: int = 42,
    ) -> None:
        """
        Initialize the alignment model.

        Parameters
        ----------
        embedding_dim : int
            Size of the representation vectors.

        num_classes : int
            Number of mental health risk categories.

        learning_rate : float
            Gradient descent learning rate.

        center_weight : float
            Weight coefficient for center loss.

        prototype_weight : float
            Weight coefficient for prototype alignment loss.

        seed : int
            Random seed for reproducibility.
        """

        np.random.seed(seed)

        self.embedding_dim = embedding_dim
        self.num_classes = num_classes
        self.learning_rate = learning_rate
        self.center_weight = center_weight
        self.prototype_weight = prototype_weight

        self.projection_matrix = np.random.randn(embedding_dim, embedding_dim) * 0.01
        self.class_centers = np.zeros((num_classes, embedding_dim))

        self.classifier_weights = np.random.randn(embedding_dim, num_classes) * 0.01
        self.classifier_bias = np.zeros(num_classes)

        self._initialized = False

    def _validate_inputs(
        self,
        representations: np.ndarray,
        labels: np.ndarray
    ) -> None:
        """
        Validate input arrays for alignment training.
        """

        if representations is None or labels is None:
            raise ValueError("Representations and labels must not be None.")

        if not isinstance(representations, np.ndarray):
            raise TypeError("Representations must be a numpy array.")

        if not isinstance(labels, np.ndarray):
            raise TypeError("Labels must be a numpy array.")

        if representations.shape[0] != labels.shape[0]:
            raise ValueError("Mismatch between number of samples and labels.")

        if representations.shape[1] != self.embedding_dim:
            raise ValueError(
                "Input representation dimension does not match model configuration."
            )

    def _softmax(self, logits: np.ndarray) -> np.ndarray:
        """
        Compute numerically stable softmax probabilities.
        """

        logits = logits - np.max(logits, axis=1, keepdims=True)
        exp_vals = np.exp(logits)
        return exp_vals / np.sum(exp_vals, axis=1, keepdims=True)

    def _cross_entropy_loss(
        self,
        probabilities: np.ndarray,
        labels: np.ndarray
    ) -> float:
        """
        Compute categorical cross-entropy loss.
        """

        n = labels.shape[0]
        eps = 1e-12
        probs = probabilities[np.arange(n), labels] + eps
        loss = -np.mean(np.log(probs))
        return loss

    def _compute_center_loss(
        self,
        embeddings: np.ndarray,
        labels: np.ndarray
    ) -> float:
        """
        Compute center loss encouraging cluster compactness.
        """

        loss = 0.0
        for i in range(embeddings.shape[0]):
            center = self.class_centers[labels[i]]
            loss += np.sum((embeddings[i] - center) ** 2)

        return loss / embeddings.shape[0]

    def _compute_prototype_loss(
        self,
        embeddings: np.ndarray,
        labels: np.ndarray
    ) -> float:
        """
        Prototype alignment loss encouraging closeness to class prototype.
        """

        loss = 0.0

        for i in range(embeddings.shape[0]):
            prototype = self.class_centers[labels[i]]
            dist = np.linalg.norm(embeddings[i] - prototype)
            loss += dist

        return loss / embeddings.shape[0]

    def _update_class_centers(
        self,
        embeddings: np.ndarray,
        labels: np.ndarray
    ) -> None:
        """
        Update class prototype centers based on current embeddings.
        """

        for c in range(self.num_classes):
            mask = labels == c
            if np.sum(mask) == 0:
                continue

            self.class_centers[c] = np.mean(embeddings[mask], axis=0)

    def _forward(
        self,
        representations: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Forward pass through projection and classifier layers.
        """

        aligned = representations @ self.projection_matrix
        logits = aligned @ self.classifier_weights + self.classifier_bias

        return aligned, logits

    def align(
        self,
        representations,
        labels
    ) -> Dict[str, float]:
        """
        Align learned representations with mental health risk categories.

        Parameters
        ----------
        representations : np.ndarray
            Latent feature representations generated by encoders or base
            models.

        labels : np.ndarray
            Target mental health severity categories (0–3).

        Returns
        -------
        Dict[str, float]
            Dictionary containing alignment loss metrics.
        """

        representations = np.asarray(representations)
        labels = np.asarray(labels).astype(int)

        self._validate_inputs(representations, labels)

        aligned, logits = self._forward(representations)

        probabilities = self._softmax(logits)

        ce_loss = self._cross_entropy_loss(probabilities, labels)

        self._update_class_centers(aligned, labels)

        center_loss = self._compute_center_loss(aligned, labels)
        prototype_loss = self._compute_prototype_loss(aligned, labels)

        total_loss = (
            ce_loss
            + self.center_weight * center_loss
            + self.prototype_weight * prototype_loss
        )

        grad_logits = probabilities
        grad_logits[np.arange(labels.shape[0]), labels] -= 1
        grad_logits /= labels.shape[0]

        grad_w = aligned.T @ grad_logits
        grad_b = np.sum(grad_logits, axis=0)

        grad_aligned = grad_logits @ self.classifier_weights.T

        grad_projection = representations.T @ grad_aligned

        self.classifier_weights -= self.learning_rate * grad_w
        self.classifier_bias -= self.learning_rate * grad_b
        self.projection_matrix -= self.learning_rate * grad_projection

        self._initialized = True

        return {
            "total_loss": float(total_loss),
            "cross_entropy_loss": float(ce_loss),
            "center_loss": float(center_loss),
            "prototype_loss": float(prototype_loss),
        }

    def transform(self, representations: np.ndarray) -> np.ndarray:
        """
        Transform representations into the aligned embedding space.

        Parameters
        ----------
        representations : np.ndarray
            Raw latent feature vectors.

        Returns
        -------
        np.ndarray
            Aligned feature representations.
        """

        if not self._initialized:
            raise RuntimeError(
                "Alignment model must be trained before calling transform()."
            )

        return representations @ self.projection_matrix

    def predict(self, features: Any) -> np.ndarray:
        """
        Predict mental health risk class using aligned representations.

        Parameters
        ----------
        features : Any
            Input feature representations.

        Returns
        -------
        np.ndarray
            Predicted class labels.
        """

        features = np.asarray(features)

        aligned = self.transform(features)
        logits = aligned @ self.classifier_weights + self.classifier_bias

        probabilities = self._softmax(logits)

        return np.argmax(probabilities, axis=1)

    def fit(self, features: Any, labels: Any) -> None:
        """
        Fit alignment model using multiple training iterations.

        Parameters
        ----------
        features : Any
            Representation matrix.

        labels : Any
            Target labels.
        """

        features = np.asarray(features)
        labels = np.asarray(labels)

        for _ in range(100):
            self.align(features, labels)